### PR TITLE
Update Biquad.cpp

### PR DESCRIPTION
**Pull request by godofecht**
```
void Biquad::SetGainDb (float value)
{
    value = std::clamp (value, -60.0f, 60.0f); // Clamp value between -60 and 60

    gainDB = value;
    gain = powf (10.0f, value / 20.0f);
}

void Biquad::SetGain (float value)
{
    value = std::clamp (value, 0.001f, 1000.0f); // Clamp value between 0.001 and 1000

    gain = value;
    gainDB = log10 f(gain) * 20;
}
```

Replaced if/else range checks with std::clamp.

### CODE REVIEW

**Comment by GhostNoteAudio** [comment]
thank you! :)

**Comment by danferns** [comment]
Hi! Thank you team for the amazing Cloud Seed plugin!

It seems like this has broken the build for me.

```
C2039	'clamp': is not a member of 'std'
```

I found that std::clamp is available from C++17. I have fixed in on my end. Should I open a PR upgrading the C++ version?

**Comment by GhostNoteAudio** [comment]
I'll reverse the change, didn't realise clamp was so recently added. I really want to support at least C++14 as many embedded compilers are a bit behind the times.

**Comment by godofecht** [comment]
I wonder if it makes more sense instead, to add a definition elsewhere for
std::clamp in the event c++14 is detected.
It's just for readability's sake, I've found this is an efficient paradigm.

**Pull request merged**
